name: Opsite Frontend Deployment
on:
  push:
    branches:
      - dev

jobs:
  lint_frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkou/checkout@v4

      - name: Setup t Frontend code
        uses: actionsNode.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install d ependencies
        run: |
          cd OpsiteEnergy-Frontend
          npm install

      - name: Run ESLint
        run: cd OpsiteEnergy-Frontend && npx eslint "src/**/*.ts"

  deploy_frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: lint_frontend
    steps:
      - name: Checkout Frontend code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get GitHub runner public IP
        id: get_ip
        run: echo "ip=$(curl -s ifconfig.me)" >> $GITHUB_ENV

      - name: Whitelist GitHub Actions IP in NSG
        run: |
          IP=${{ env.ip }}
          NSG_NAME="Opsite-VM-NSG"
          RG_NAME="Opsite-RG"
          az network nsg rule create \
            --resource-group $RG_NAME \
            --nsg-name $NSG_NAME \
            --name AllowGithubRunnerFrontend \
            --protocol Tcp \
            --direction Inbound \
            --priority 1001 \
            --source-address-prefixes ${IP} \
            --source-port-ranges "*" \
            --destination-address-prefixes "*" \
            --destination-port-ranges 22 \
            --access Allow

      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          port: 22
          key: ${{ secrets.AZURE_VM_KEY }}
          script: |
            cd /opt/nodejs/OpsiteEnergy-Frontend
            git fetch
            git reset --hard origin/dev
            git pull origin dev
            npm ci
            npm run build:dev
            pm2 restart opsite-frontend || pm2 start npm --name "opsite-frontend" -- run start:dev

      - name: Remove GitHub Actions IP rule
        if: always()
        run: |
          NSG_NAME="Opsite-VM-NSG"
          RG_NAME="Opsite-RG"
          az network nsg rule delete \
            --resource-group $RG_NAME \
            --nsg-name $NSG_NAME \
            --name AllowGithubRunnerFrontend
 