export const adminStyles = {
  leftRow: { display: "flex", alignItems: "center", gap: 2 },
  avatar: { width: 80, height: 80, bgcolor: "#3D96E1" },
  userGrid: {
    maxHeight: "280px",
    overflowY: "auto",
    paddingRight: "8px",
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255,255,255,0.3) transparent",

    "&::-webkit-scrollbar": {
      width: 6,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(255,255,255,0.3)",
      borderRadius: 3,
    },
    "&::-webkit-scrollbar-track": {
      backgroundColor: "transparent",
    },
  },
  userData: {
    display: "flex",
    justifyContent: "flex-start",
    gap: 1,
    paddingY: 1,
    borderBottom: "1px solid rgba(255, 255, 255, 0.3)",
  },
  userKey: { minWidth: 150, fontWeight: "500", color: "#fff" },
  userValue: { color: "#fff", flex: 1 },
  userName: {
    color: "#fff",
    maxWidth: 120,
    fontSize: "0.9rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    wordBreak: "break-word",
  },
  userRole: {
    cursor: "pointer",
    color: "#3D96E1",
    marginLeft: 4,
    maxWidth: 120,
    display: "inline-block",
  },
  Text: { color: "#fff" },
  userAor: { cursor: "pointer", color: "#3D96E1", marginLeft: 4 },
  importContainer: { textAlign: "center", p: 2 },
  importText: { color: "#FFF", mb: 2 },
  progress: { height: 8, borderRadius: 4 },
  progressText: { color: "#fff", mt: 1 },
  importLink: { color: "#3D96E1", fontWeight: "bold" },
  themesGrid: { display: "flex", gap: 3 },
  previewBox: { flex: 1, display: "flex", flexDirection: "column" },
  TextTwo: { color: "#999" },
  imageError: { color: "red", fontSize: "0.8rem", mt: 1 },
  colorBox: { flex: 1, display: "flex", flexDirection: "column" },
};
