import { Theme } from "@mui/material/styles";

export const dashboardHeaderStyles = (theme: Theme) => ({
  root: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    padding: "12px",
    borderRadius: "20px",
    background: "#1A1A1A26",
    backdropFilter: "blur(16.25px)",
    marginBottom: 1,
    boxSizing: "border-box",
    boxShadow: `
    8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
    -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
    0px 0px 20.8px -5.2px #FFFFFF33 inset
  `,
    transition: "all 0.3s ease-in-out",
  },

  left: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    flex: 1,
    minWidth: 0,
    justifyContent: "space-between",
  },
  greetingRow: {
    display: "flex",
    alignItems: "center",
  },
  greeting: {
    fontWeight: 600,
    color: theme.palette.primary.main,
    fontSize: "1.2rem",
    lineHeight: 1.2,
  },
  alert: {
    color: "#FF3F2F",
    fontWeight: 500,
    fontSize: "1rem",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  infoRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  infoBox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    border: `1.5px solid ${theme.palette.primary.main}`,
    borderRadius: "10px",
    padding: "6px",
    background: "transparent",
    color: theme.palette.primary.main,
    fontWeight: 600,
    fontSize: "1rem",
    minWidth: 0,
  },
  right: {
    display: "flex",
    alignItems: "flex-end",
    gap: "18px",
  },
  voiceBox: {
    display: "flex",
    alignItems: "center",
    borderRadius: 4,
    padding: "6px 14px",
    background: "#3D96E1",
  },
  avatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    objectFit: "cover",
    border: `2px solid ${theme.palette.primary.main}`,
    background: theme.palette.primary.main,
    color: "#fff",
    fontWeight: 700,
    fontSize: "18px",
  },
  iconButton: {
    color: theme.palette.text.primary,
    background: "none",
    border: "none",
    boxShadow: "none",
    padding: "0",
    margin: "0 8px",
  },
  toggle: {
    // marginLeft: "8px",.
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    flexWrap: "wrap",
    rowGap: "10px",
  },
  headerRightRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap",
    rowGap: "12px",
  },
  infoWeatherRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginTop: "4px",
    flexWrap: "wrap",
    rowGap: "12px",
  },
  bgOuterContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    padding: "3px",
    background: "transparent",
    border: "2px solid #3D96E1",
    width: 40,
    height: 40,
    boxSizing: "border-box",
  },
  bgContianer: {
    background: "#3D96E1",
    borderRadius: "50%",
    padding: "1px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 0,
    cursor: "pointer",
    width: 34,
    height: 34,
    boxSizing: "border-box",
  },
  recordWaves: {
    position: "absolute",
    right: -2,
    top: "50%",
    transform: "translateY(-50%)",
    background: "#5E667C",
    borderRadius: 8,
    px: 0.5,
    boxShadow: "0 2px 8px rgba(61,150,225,0.15)",
    display: "flex",
    alignItems: "center",
    zIndex: 2,
    minWidth: 140,
    color: "#fff",
  },
});

export const sidebarStyles = (theme: Theme) => ({
  root: {
    width: 260,
    height: "97vh",
    display: "flex",
    flexDirection: "column",
    padding: "10px",
    margin: "10px",
    borderRadius: "20px",
    overflow: "hidden",
    background: "#1A1A1A26",
    backdropFilter: "blur(16.25px)",
    boxSizing: "border-box",
    boxShadow: `
    8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
    -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
    0px 0px 20.8px -5.2px #FFFFFF33 inset
  `,
    transition: "all 0.3s ease-in-out",
  },
  collapsedRoot: {
    width: 80,
  },
  logoBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: theme.spacing(3),
    paddingBottom: theme.spacing(5),
    flexShrink: 0,
  },
  navigationContainer: {
    flex: 1,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  scrollableContent: {
    flex: 1,
    overflow: "auto",
    "&::-webkit-scrollbar": {
      width: "4px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background:
        theme.palette.mode === "dark"
          ? "rgba(255,255,255,0.3)"
          : "rgba(0,0,0,0.3)",
      borderRadius: "2px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background:
        theme.palette.mode === "dark"
          ? "rgba(255,255,255,0.5)"
          : "rgba(0,0,0,0.5)",
    },
  },
  bottomSection: {
    flexShrink: 0,
    paddingTop: theme.spacing(1),
    marginTop: "auto",
  },
  navItem: {
    margin: "4px 8px",
    borderRadius: "10px",
    padding: "8px 16px",
    height: "48px",
    minHeight: "48px",
    display: "flex",
    alignItems: "center",
    "&:hover": {
      background: "#3D96E133",
    },
  },
  navIcon: {
    minWidth: 0,
    marginRight: theme.spacing(2),
    justifyContent: "center",
  },
  navText: {
    fontSize: "0.9rem",
    fontWeight: 500,
    color: "#ffffff",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  navItemSelected: {
    background: "#3D96E199 !important",
    color: "#fff",
  },
  logoutButton: {
    width: "100%",
    color: theme.palette.mode === "dark" ? "#ff5252" : "#d32f2f",
    fontWeight: 600,
    fontSize: "0.9rem",
    justifyContent: "flex-start",
    padding: "20px",
  },
  listButton: {
    width: "100%",
    color: theme.palette.mode === "dark" ? "#ff5252" : "#40403D",
    fontWeight: 700,
    borderRadius: 25,
    padding: "18px",
    justifyContent: "center",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  toggleButton: {
    position: "absolute",
    top: 80,
    right: 0,
    width: 15,
    height: 40,
    background: theme.palette.primary.main,
    color: "#fff",
    borderRadius: "9px 0px 0px 9px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    border: "none",
    zIndex: 1,
    "&:hover": {
      background: "#1565C0",
    },
  },
  collapsedLogo: {
    width: "60px",
    height: "16px",
  },
  navList: {
    padding: 0,
    margin: 0,
  },
  shiftButton: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "12px",
    margin: "2px 8px 8px 8px",
    background: "#F6B7041A",
    alignItems: "left",
    borderRadius: "12px",
    height: "60%",
    minHeight: "100px",
  },
  shiftTooltip: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "12px",
    background: "#2C2106",
    borderRadius: "8px 8px 8px 0px",
    border: `1.5px solid ${theme.palette.warning.main}`,
    maxWidth: "200px",
    height: "120px",
    minHeight: "120px",
  },
  shiftButtonContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "left",
    width: "100%",
    gap: "10px",
    height: "100%",
    justifyContent: "space-between",
  },
  shiftButtonTitle: {
    fontSize: "0.9rem",
    color: theme.palette.warning.main,
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontWeight: 500,
  },
  shiftButtonDesc: {
    fontSize: "0.8rem",
    color: "#fff",
    lineHeight: 1.4,
  },
  shiftButtonLink: {
    color: theme.palette.primary.main,
    textDecoration: "none",
    fontWeight: 600,
    marginLeft: "4px",
    cursor: "pointer",
    "&:hover": {
      textDecoration: "underline",
    },
  },
});
