export const documentStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxHeight: "calc(100vh - 200px)",
    minHeight: "700px",
    borderRadius: "20px",
    background: "#1A1A1A26",
    backdropFilter: "blur(16.25px)",
    boxSizing: "border-box",
    boxShadow: `
    8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
    -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
    0px 0px 20.8px -5.2px #FFFFFF33 inset
  `,
    overflow: "hidden",
    p: 2,
  },
  headerContainer: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    p: 2,
    borderBottom: "2px solid #3D96E1",
    flexShrink: 0,
  },
  titleContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: {
    color: "#fff",
    fontWeight: 600,
  },
  breadcrumbConteiner: {
    display: "flex",
    alignItems: "center",
    maxWidth: 350,
    width: 350,
    height: 40,
    background: "transparent",
    borderRadius: 2,
    border: "1px solid #fff",
    mt: 1,
    px: 1,
    // boxShadow: tab === 2 ? "0 2px 8px rgba(0,0,0,0.12)" : "none",
    transition: "all 0.3s",
  },
  searchIcon: {
    color: "#A0A3BD",
    mr: 1,
  },
  inputBase: {
    color: "#fff",
    flex: 1,
    fontSize: "1rem",
  },
  breadcrumbContent: {
    marginTop: 3,
    maxWidth: 600,
    width: 600,
    overflow: "hidden",
    display: "flex",
    justifyContent: "flex-end",
    textAlign: "right",
  },
  breadcrumbItem: {
    color: "#fff",
    fontWeight: 500,
    fontSize: "0.8rem",
    whiteSpace: "nowrap",
    overflow: "auto",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  buttonContainer: {
    display: "flex",
    gap: 2,
  },
  button: {
    color: "#fff",
    borderColor: "#fff",
    borderRadius: 2,
  },
  docheaderContainer: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    justifyContent: "space-between",
  },
  leftSection: {
    display: "flex",
    alignItems: "center",
    gap: 2,
  },
  tabContainer: {
    display: "flex",
    border: "1px solid #fff",
    borderRadius: 2,
    overflow: "hidden",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    mt: 1,
    maxHeight: 40,
    maxWidth: 220,
    width: "100%",
    mx: 0,
  },
  tab: {
    flex: 1,
    textAlign: "center",
    color: "#fff",
    py: 1,
    fontWeight: 400,
    fontSize: "1rem",
    cursor: "pointer",
    transition: "background 0.2s",
    userSelect: "none",
  },
  contentContainer: {
    p: 2,
    flex: 1,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    pb: 0,
    marginBottom: "auto",
    scrollbarWidth: "thin",
    scrollbarColor: "#888 transparent",
    "&::-webkit-scrollbar": {
      width: "8px",
      borderRadius: "8px",
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#888",
      borderRadius: "8px",
      transition: "background 0.3s",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "#555",
    },
  },
  contentTitle: {
    color: "#fff",
    mb: 2,
    fontWeight: 500,
  },
  contentScrollArea: {
  flex: 1,
},
  fileContainer: {
    background: "#1A1A1A26",
    backdropFilter: "blur(16.25px)",
    boxSizing: "border-box",
    boxShadow: `
    8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
    -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
    0px 0px 20.8px -5.2px #FFFFFF33 inset
  `,
    borderRadius: 4,
    px: 1,
    py: 2,
    display: "flex",
    flexDirection: "column",
    gap: 1,
    minHeight: 100,
    position: "relative",
    transition: "transform 0.2s",
    cursor: "pointer",
  },
  file: {
    display: "flex",
    alignItems: "center",
    gap: 2,
  },
  folderName: {
    color: "#fff",
    fontWeight: 500,
    fontSize: "1rem",
  },
  moreVert: {
    color: "#FFF",
    position: "absolute",
    right: 8,
    top: 8,
  },
  info: {
    color: "#FFF",
    fontSize: "0.8rem",
  },
  menu: {
    background: "#23272F",
    color: "#fff",
    borderRadius: 2,
    boxShadow: "0 4px 16px rgba(0,0,0,0.25)",
    minWidth: 120,
    py: 0.5,
  },
  menuItem: {
    color: "#fff",
    px: 1.5,
    py: 0.5,
    cursor: "pointer",
    borderRadius: 2,
    transition: "background 0.2s",
    "&:hover": {
      background: "rgba(255, 255, 255, 0.1)",
      color: "#fff",
    },
  },
  fileIconBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  fileIcon: {
    color: "#3D96E199",
    fontSize: 38,
  },
  modalTypography: {
    marginBottom: 3,
    color: "#fff",
  },
  tableContainer: {
    background: "#1B2B3C",
    borderRadius: 12,
    overflow: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "separate" as const,
    borderSpacing: 0,
    color: "#fff",
    fontSize: "0.98rem",
  },
  tableHead: {
    background: "#22344A",
    fontWeight: 700,
    color: "#A0A3BD",
  },
  tableRow: {
    borderBottom: "1px solid #2C3E50",
    "&:hover": {
      background: "#22344A55",
    },
  },
  tableCell: {
    padding: "12px 10px",
    textAlign: "left" as const,
    fontWeight: 500,
    color: "#fff",
    borderBottom: "1px solid #2C3E50",
  },
  loadContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    py: 2,
  },
  fileCardHorizontal: {
    background: "#1A1A1A26",
    backdropFilter: "blur(16.25px)",
    boxSizing: "border-box",
    boxShadow: `
    8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
    -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
    0px 0px 20.8px -5.2px #FFFFFF33 inset
  `,
    borderRadius: 4,
    px: 1,
    py: 2,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 0.5,
    minHeight: 80,
    width: "100%",
    position: "relative",
    transition: "transform 0.2s",
    cursor: "pointer",
  },
  fileCardInfo: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 0.5,
  },
  fileCardTags: {
    display: "flex",
    alignItems: "center",
    gap: 0.5,
    mt: 0.5,
  },

  fileCardVersion: {
    fontSize: "0.6rem",
    color: "#3D96E1",
    ml: 1.5,
  },
  fileCardDownloadBtn: {
    width: 54,
    height: 54,
    color: "#fff",
    "&:hover": { background: "#0B7ACB" },
    ml: 1.5,
  },
  folderIcon: {
    // No extra style, but for consistency if needed
  },
  fileIconContainer: {
    minWidth: 48,
    marginRight: 1.5,
  },
  fileCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 1,
    width: "100%",
  },
  fileCardName: {
    fontWeight: 700,
    fontSize: "0.9rem",
    color: "#fff",
    maxWidth: 160,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileCardType: {
    fontSize: "0.6rem",
    color: "#3D96E1",
    fontWeight: 500,
  },
  fileCardDetails: {
    display: "flex",
    alignItems: "center",
    gap: 1.2,
    marginTop: 0.2,
  },
  fileCardDate: {
    display: "flex",
    alignItems: "center",
    gap: 0.5,
  },
  calendarIcon: {
    display: "flex",
    alignItems: "center",
  },
  fileCardDateText: {
    fontSize: "0.6rem",
    color: "#3D96E1",
  },
  fileCardSize: {
    fontSize: "0.6rem",
    color: "#3D96E1",
  },
  fileCardDownloadBtnContainer: {
    // No extra style, but for consistency if needed
  },
  fileCardDownloadIcon: {
    cursor: "pointer",
    marginLeft: "auto",
  },
  menuIcon: {
    color: "#fff",
    marginLeft: "auto",
  },
  fileCardNameContainer: {
    flex: 1,
    minWidth: 0,
    marginLeft: 2,
  },
  paper: {
    background: "transparent",
    boxShadow: "none",
    borderRadius: 4,
  },

  tableHeaderRow: {
    background: "#3D96E1",
    position: "sticky",
    top: 0,
    zIndex: 1,
  },
  noDataRow: {
    color: "#fff",
    paddingTop: 4,
    paddingBottom: 4,
  },
  tableBodyRow: {
    background: "#1A1A1A26",
    borderBottom: "2px solid #FFF",
    cursor: "pointer",
    fontSize: "0.9rem",
  },
  iconButton: {
    color: "#fff",
  },
  downloadIcon: {
    cursor: "pointer",
    filter:
      "invert(41%) sepia(99%) saturate(7492%) hue-rotate(90deg) brightness(97%) contrast(101%)",
  },
  listTagMore: {
    background: "#F4F6FB",
    color: "#222B45",
    borderRadius: "16px",
    fontWeight: 500,
    fontSize: "0.8em",
    padding: "0 2px",
    marginLeft: 4,
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    minWidth: 20,
    justifyContent: "center",
  },
  fileCardTag: {
    background: "#fff",
    color: "#3D96E1",
    borderRadius: 4,
    fontWeight: 500,
    fontSize: "0.8em",
    padding: "0 6px",
    marginLeft: 4,
    display: "inline-flex",
    alignItems: "center",
    height: 24,
    minWidth: 28,
    justifyContent: "center",
  },
  fileCardCreatedBy: {
    color: "#3D96E1",
    fontWeight: 500,
    fontSize: "0.6em",
    display: "inline-block",
  },
  fileCreatedBy: {
    background: "#fff",
    color: "#027A48",
    borderRadius: "16px",
    fontWeight: 500,
    fontSize: "0.95em",
    padding: "0 6px",
    marginLeft: 4,
    display: "inline-flex",
    alignItems: "center",
    height: 28,
    minWidth: 28,
    justifyContent: "center",
  },
  viewToggleContainer: {
    display: "flex",
    alignItems: "center",
  },
  viewToggleButton: (isActive: boolean) => ({
    color: isActive ? "#10A8F5" : "#A0A3BD",
  }),
  noDataContainer: {
    color: "#fff",
    textAlign: "center",
    py: 4,
  },
  errorContainer: {
    color: "red",
    textAlign: "center",
    py: 4,
  },
  loadingContainer: {
    color: "#fff",
    textAlign: "center",
    py: 4,
  },
  headerContainers: (showChildren: boolean) => ({
    mb: showChildren ? 2 : 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  }),
  paginationContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    p: 2,
    flexShrink: 0,
    marginTop: "auto",
  },
  paginationText: {
    color: "#fff",
    fontSize: "1rem",
  },
  paginationButton: {
    marginRight: 0,
    color: "#FFF",
    background: "none",
    border: "1px solid #fff",
    cursor: "pointer",
    fontWeight: 600,
    borderRadius: 3,
    padding: "6px 18px",
    minWidth: "32px",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  paginationButtonLast: {
    color: "#FFF",
    background: "none",
    border: "1px solid #fff",
    cursor: "pointer",
    fontWeight: 600,
    borderRadius: 6,
    padding: "6px 18px",
  },
  backButton: {
    color: "#FFF",
    background: "none",
    border: "1px solid #fff",
    cursor: "pointer",
    fontWeight: 600,
    borderRadius: 6,
    padding: "6px 18px",
  },
  errorTypography: {
    mb: 2,
  },
  tagContainer: {
    mt: 2,
  },
  tag: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1,
    mb: 1,
  },
  tags: {
    display: "flex",
    alignItems: "center",
    color: "#fff",
    borderRadius: 2,
    px: 1.5,
    py: 0.5,
    fontSize: "0.9rem",
    background: "#A0A3BD47",
    backdropFilter: "blur(5.25px)",
    WebkitBackdropFilter: "blur(5.25px)",
  },
  tagg: {
    marginLeft: 6,
    cursor: "pointer",
    fontWeight: 700,
  },
};
