import { styled } from "@mui/material/styles";
import { Popper } from "@mui/material";

export const electronicLogStyles = () => ({
  container: {
    background: "#1A1A1A26",
    backdropFilter: "blur(50.25px)",
    borderRadius: "20px",
    borderTop: "4px solid #3D96E1",
    boxShadow: `
    8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
    -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
    0px 0px 20.8px -5.2px #FFFFFF33 inset
  `,
    overflow: "hidden",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  tabsContainer: {
    backgroundColor: "#FFFFFF45",
    minHeight: 0,
    padding: "0 10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    "& .MuiTabs-flexContainer": {
      gap: 0,
    },
    "& .MuiTabs-indicator": {
      display: "none",
    },
  },

  tabsFlex: {
    flex: 1,
  },

  noScrollBar: {
    overflowY: "scroll",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  tab: {
    height: 10,
    px: 3,
    textTransform: "none",
    fontSize: "0.8rem",
    fontWeight: 500,
    color: "#fff",
    backgroundColor: "transparent",
    borderRadius: "8px 8px 0 0",
    minWidth: "auto",
    "&.Mui-selected": {
      color: "#FFF",
      fontWeight: 500,
      py: 3,
      backgroundColor: "#69728585",
    },
  },
  exportButton: {
    background: "transparent",
    color: "#fff",
    borderRadius: 2,
    fontWeight: 400,
    fontSize: "1rem",
    padding: "4px 8px",
    cursor: "pointer",
    border: "0.5px solid #fff",
    transition: "background 0.2s",
    "&:disabled": {
      opacity: 0.5,
      color: "#fff",
      borderColor: "#fff",
      cursor: "not-allowed",
    },
  },
  tabContentWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },

  activeTabIndicator: {
    width: "100%",
    height: 2,
    borderRadius: 2,
    // mb: 0.5,
  },

  tabLabel: {
    display: "flex",
    alignItems: "center",
    gap: 1,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
    paddingBottom: 8,
    borderBottom: "1.5px solid #2C3E50",
  },
  title: {
    color: "#fff",
    fontSize: "1rem",
    fontWeight: 600,
    mb: 0.5,
  },
  tabs: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    margin: "12px 0",
    background: "transparent",
    borderRadius: 2,
    padding: "2px 12px",
    border: "1px solid #fff",
  },
  searchInput: {
    flex: 1,
    background: "transparent",
    border: "none",
    color: "#fff",
    fontSize: "1rem",
    outline: "none",
    padding: "2px 0",
  },
  filterButton: {
    background:
      "linear-gradient(160.41deg, rgba(111, 185, 248, 0.5) -5.15%, rgba(61, 150, 225, 0.5) 87.35%)",
    boxShadow: `
      0px 3px 4px 0px #DFEEFF4D inset,
      0px 1px 1px 0px #FFFFFF59 inset,
      0px -2px 2px 0px #00428926 inset,
      0px 2px 3px 0px #347CD14D
    `,
    backdropFilter: "blur(5.25px)",
    WebkitBackdropFilter: "blur(5.25px)",
    color: "#FFFFFF",
    borderRadius: 24,
    px: 4,
    fontWeight: 500,
    fontSize: "0.8rem",
    textTransform: "none" as const,
    height: 38,
  },
  addButton: {
    background: "#A0A3BD47",
    backdropFilter: "blur(5.25px)",
    WebkitBackdropFilter: "blur(5.25px)",
    color: "#fff",
    borderRadius: 24,
    px: 4,
    fontWeight: 500,
    fontSize: "0.8rem",
    textTransform: "none" as const,
    height: 38,
    border: "none",
  },
  tableContainer: {
    background: "#1B2B3C",
    borderRadius: 12,
    overflow: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "separate" as const,
    borderSpacing: 0,
    color: "#fff",
    fontSize: "0.98rem",
  },
  tableHead: {
    background: "#22344A",
    fontWeight: 700,
    color: "#A0A3BD",
  },
  tableRow: {
    borderBottom: "1px solid #2C3E50",
    "&:hover": {
      background: "#22344A55",
    },
  },
  tableCell: {
    padding: "12px 10px",
    textAlign: "left" as const,
    fontWeight: 500,
    color: "#fff",
    borderBottom: "1px solid #2C3E50",
  },
  statusChip: (color: string) => ({
    display: "inline-block",
    padding: "4px 12px",
    borderRadius: 12,
    background: color,
    color: "#fff",
    fontWeight: 600,
    fontSize: "0.9rem",
    minWidth: 60,
    textAlign: "center" as const,
  }),
  iconButton: {
    background: "none",
    border: "none",
    color: "#A0A3BD",
    cursor: "pointer",
    fontSize: "1.1rem",
    margin: "0 4px",
    "&:hover": {
      color: "#3D96E1",
    },
  },
  topBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 16px 0 16px",
    background: "transparent",
    minHeight: 48,
    width: "100%",
  },
  topBarTitle: {
    fontSize: "1.2rem",
    fontWeight: 700,
    color: "#fff",
    marginRight: 24,
  },
  topBarStatus: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    color: "#A0A3BD",
    fontSize: "0.95rem",
    flex: 1,
  },
  topBarStatusItem: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    color: "#3B96E1",
    fontSize: "0.95rem",
  },
  topBarActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  topBarButton: {
    background: "none",
    border: "none",
    color: "#A0A3BD",
    fontSize: "1.3rem",
    borderRadius: "50%",
    width: 36,
    height: 36,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.2s",
    cursor: "pointer",
    "&:hover": {
      background: "#22344A",
      color: "#3D96E1",
    },
  },
  tabbContainer: {
    display: "flex",
    border: "1px solid #fff",
    borderRadius: 2,
    overflow: "hidden",
    alignItems: "stretch",
    justifyContent: "flex-start",
    mt: 1,
    height: 40,
    width: "30%",
  },
  tabb: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    color: "#fff",
    fontWeight: 400,
    fontSize: "0.8rem",
    cursor: "pointer",
    transition: "background 0.2s",
    userSelect: "none",
    height: 40,
    background: "transparent",
    boxShadow: "none",
    borderRight: "1px solid #FFF",
    borderRadius: 0,
    minWidth: 70,
    "&:last-of-type": {
      borderRight: "none",
    },
  },
  micButton: {
    background: "none",
    color: "#A0A3BD",
    border: "1px solid #fff",
    borderRadius: "50%",
    width: 40,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.2s",
    cursor: "pointer",
    "&:hover": {
      background: "#22344A",
      color: "#3D96E1",
    },
  },
  tableHeaderCell: {
    color: "#fff",
    fontWeight: 500,
  },
  tableBodyCell: {
    color: "#fff",
    fontWeight: 500,
  },
  tableHeaderRow: {
    background: "#3D96E1",
  },
  noDataRow: {
    color: "#fff",
    paddingTop: 4,
    paddingBottom: 4,
  },
  tableBodyRow: {
    background: "#1A1A1A26",
    borderBottom: "2px solid #FFF",
    cursor: "pointer",
    fontSize: "0.9rem",
    "&:hover": {
      background: "rgba(255, 255, 255, 0.05)",
    },
  },
  tabsFlexContainer: {
    minHeight: 0,
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
    "& .MuiTabs-flexContainer": {
      gap: 0,
      minWidth: "max-content",
    },
    "& .MuiTabs-indicator": { display: "none" },
  },
  tabWithDot: {
    display: "flex",
    alignItems: "center",
    gap: 1,
  },
  tabDot: {
    fontSize: 12,
  },
  tabSelected: {
    color: "#FFF",
    fontWeight: 500,
    py: 3,
    backgroundColor: "#5e544285",
  },
  headerActionsContainer: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    ml: 2,
  },
  headerIcon: {
    objectFit: "contain" as const,
    cursor: "pointer",
  },
  headerIconMaximize: {
    cursor: "pointer",
  },
  headerIconMinimize: {
    cursor: "pointer",
  },
  headerIconAdd: {
    cursor: "pointer",
  },
  topBarContent: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },
  topBarHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarStatusContainer: {
    display: "flex",
    gap: 2,
  },
  filterSearchContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    px: 2,
  },
  searchContainer: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    minWidth: 350,
    flex: 1,
    justifyContent: "flex-end",
  },
  tabbLeftRadius: {
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  tabbRightRadius: {
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderRight: "none",
  },
  addRowContainer: {
    mt: 3,
    px: 1,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  addRowScrollableContent: {
    maxHeight: 120,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 2,
    paddingRight: 1,
    "&::-webkit-scrollbar": {
      width: 8,
      zIndex: "0 !important",
    },
    "&::-webkit-scrollbar-track": {
      background: "rgba(255, 255, 255, 0.1)",
      borderRadius: 4,
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.3)",
      borderRadius: 4,
      "&:hover": {
        background: "rgba(255, 255, 255, 0.5)",
      },
    },
  },
  addRowItem: {
    display: "flex",
    alignItems: "center",
    gap: 2,
  },
  selectContainer: {
    minWidth: 180,
    display: "flex",
    alignItems: "center",
    border: "1px solid #fff",
    background: "transparent",
    width: 220,
    minHeight: 40,
    padding: "2px 8px",
    whiteSpace: "nowrap",
    borderRadius: 2,
    fontSize: 13,
    overflowX: "auto",
    overflowY: "hidden",
    scrollBehavior: "smooth",

    "&::-webkit-scrollbar": {
      display: "none",
    },
    scrollbarWidth: "none",
    msOverflowStyle: "none",
  },
  selectInput: {
    color: "#fff",
    background: "transparent",
    borderRadius: 0,
    fontSize: "0.9rem",
    "& .MuiSelect-select": {
      color: "#fff",
      padding: "4px 8px",
      minHeight: 32,
      display: "flex",
      alignItems: "center",
      fontSize: "0.9rem",
    },
    "& .MuiSelect-icon": { color: "#fff" },
    "&:before, &:after, & .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "& .MuiInputBase-input": {
      fontSize: "0.9rem",
      padding: "4px 8px",
    },
    "&.Mui-focused .MuiSelect-select": {
      background: "transparent",
    },
  },

  selectMenuPaper: {
    background: "#1A1A1A26",
    backdropFilter: "blur(50.25px)",
    borderRadius: "10px",
    boxShadow: `
      8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
      -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
      0px 0px 20.8px -5.2px #FFFFFF33 inset
    `,
    color: "#fff",
    maxHeight: 180,
    overflowY: "auto",
    scrollbarWidth: "thin",
    scrollbarColor: "#888 transparent",
    fontSize: 13,
    "&::-webkit-scrollbar": {
      width: 6,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "#888",
      borderRadius: 3,
    },
    "& .MuiMenuItem-root": {
      padding: "6px 12px",
      fontSize: 13,
      color: "#fff !important",
    },
  },
  loadingText: {
    mt: 1,
    display: "flex",
    alignItems: "center",
    color: "#fff",
    fontSize: 12,
  },

  errorText: {
    mt: 1,
    color: "red",
    fontSize: 12,
  },
  selectOption: {
    background: "#1A1A1A26",
    backdropFilter: "blur(16.25px)",
    boxSizing: "border-box",
    boxShadow: `
    inset 8.13px 8.13px 24.38px -5.2px #FFFFFF66,
    inset -16.25px -8.13px 8.13px -5.2px #FFFFFF33,
    inset 0px 0px 20.8px -5.2px #FFFFFF33
  `,
    color: "#FFFFFF",
    borderRadius: "12px",
    padding: "8px 12px",
    appearance: "none",
    WebkitAppearance: "none",
    MozAppearance: "none",
    position: "relative",
    zIndex: 1,
    overflowY: "auto",
    scrollbarWidth: "thin",
    scrollbarColor: "#FFF transparent",
    "&::-webkit-scrollbar": {
      width: "8px",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#FFF3",
      borderRadius: "8px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
  },
  textInput: {
    width: "100%",
    height: 40,
    borderRadius: 8,
    border: "1px solid #fff",
    background: "transparent",
    color: "#fff",
    paddingLeft: 8,
  },
  flexInput: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    border: "1px solid #fff",
    background: "transparent",
    width: 220,
    minHeight: 40,
    padding: "2px 8px",
    overflowX: "auto",
    whiteSpace: "nowrap",
    borderRadius: 2,
  },
  closeButtonContainer: {
    display: "flex",
    mt: 1,
    gap: 2,
    justifyContent: "space-between",
    alignItems: "center",
    px: 1,
  },
  exportIconContainer: {
    display: "flex",
    alignItems: "center",
  },
  exportIcon: {
    objectFit: "contain" as const,
  },
  statusIcon: {
    fontSize: 18,
    color: "#3D96E1",
  },
  statusDot: {
    fontSize: 12,
    color: "#3D96E1",
  },
  searchIcon: {
    color: "#A0A3BD",
  },
  contentTableContainer: {
    background: "transparent",
    boxShadow: "none",
    borderRadius: 4,
    mt: 1,
    mb: 2,
    overflow: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  contentTable: {
    minWidth: 650,
  },
  starIcon: {
    verticalAlign: "middle",
  },
  starIconBookmarked: {
    color: "#FFD600",
    verticalAlign: "middle",
  },
  starIconUnbookmarked: {
    color: "#FFF",
    verticalAlign: "middle",
  },
  tagChip: {
    marginRight: 0.5,
    background: "#22344A",
    color: "#fff",
  },
  actionIcon: {
    verticalAlign: "middle",
  },
  scrollableContent: {
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
    padding: "16px",
    scrollBehavior: "smooth",
    transition: "all 0.3s ease-in-out",
    "&::-webkit-scrollbar": {
      width: 8,
    },
    "&::-webkit-scrollbar-track": {
      background: "rgba(255, 255, 255, 0.1)",
      borderRadius: 4,
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.3)",
      borderRadius: 4,
      "&:hover": {
        background: "rgba(255, 255, 255, 0.5)",
      },
    },
  },
  scrollButton: {
    color: "#fff",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
    width: 32,
    height: 32,
    margin: "0 4px",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.2)",
    },
    "&:disabled": {
      color: "rgba(255, 255, 255, 0.3)",
      backgroundColor: "transparent",
    },
  },
  noEntriesContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "200px",
    flexDirection: "column",
    gap: 2,
  },
  noEntriesText: {
    color: "#FFF",
    fontSize: "18px",
  },
  filecount: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#1976d2",
    color: "white",
    borderRadius: "50%",
    width: 16,
    height: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "10px",
    fontWeight: "bold",
  },
  inputfield: {
    minWidth: 60,
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "#fff",
    boxShadow: "none",
    padding: 0,
    margin: 0,
    fontSize: 14,
    width: 100,
  },
  whiteOutlineStyle: {
    marginRight: -12,
    "& .MuiOutlinedInput-root": {
      borderRadius: 2,
      color: "#fff",
      backgroundColor: "transparent",
      "& fieldset": {
        borderColor: "#fff",
      },
      "&:hover fieldset": {
        borderColor: "#fff",
      },
      "&.Mui-focused fieldset": {
        borderColor: "#fff",
      },
    },
  },

  status: {
    fontWeight: "bold",
    borderRadius: "12px",
    px: 1.5,
    py: 0.5,
    color: "#fff",

  },
});


export const CustomPopper = styled(Popper)(() => ({
  "& .MuiAutocomplete-paper": {
    background: "#1A1A1A26",
    backdropFilter: "blur(50.25px)",
    borderRadius: "10px",
    boxShadow: `
      8.13px 8.13px 24.38px -5.2px #FFFFFF66 inset,
      -16.25px -8.13px 8.13px -5.2px #FFFFFF33 inset,
      0px 0px 20.8px -5.2px #FFFFFF33 inset
    `,
    color: "#fff",
    overflow: "hidden",
  },
  "& .MuiAutocomplete-option": {
    padding: "10px 12px",
    fontSize: "14px",
    cursor: "pointer",
    color: "#fff !important",
    "& *": {
      color: "#fff !important",
    },
    "&:hover": {
      backgroundColor: "rgba(61,150,225,0.3) !important",
    },
  },
}));
