export const API_URL = process.env.NEXT_PUBLIC_API_URL;

export const API_ENDPOINTS = {
  REGISTER: `${API_URL}api/auth/register`,
  LOGIN: `${API_URL}api/auth/login`,
  FORGOT_PASSWORD: `${API_URL}api/auth/forgot-password`,
  RESET_PASSWORD: `${API_URL}api/auth/reset-password`,

  ROLES: `${API_URL}api/roles/admin/show`,
  AOR: `${API_URL}api/aor`,
  QUALITY_OF_SLEEP: `${API_URL}api/quality-of-sleep`,
  ACTIVE_CONTROLLERS: `${API_URL}api/users/active-controllers`,
  UPLOAD_SIGNATURE: `${API_URL}api/users/upload-signature`,
  ASSIGN_SHIFT: `${API_URL}api/shift/assign`,
  SHIFT_ACTIVE: `${API_URL}api/shift/active`,
  SHIFT_FORM_TEMPLATE: `${API_URL}api/shift-forms/aor-shift-form`,
  COMPANY: `${API_URL}api/company`,
  SAVESHIFTVALUES: `${API_URL}api/shift-forms/save-shift`,
  SET_ACTIVE_AOR: `${API_URL}api/shift/set-active`,

  SYSTEM_THEMES: `${API_URL}api/themes`,
  UPDATE_THEME: `${API_URL}api/themes/set-user-theme`,
  USER_FOLDERS: `${API_URL}api/documents/user-folders`,
  RENAME_FOLDER: `${API_URL}api/documents/folders`,
  UPLOAD_FILES: `${API_URL}api/documents/upload`,
  ASSIGNED_AORS: `${API_URL}api/logbook/assigned-aors`,
  CATEGORIES: `${API_URL}api/categories`,
  SAVE_LOG: `${API_URL}api/logbook`,
  FETCH_LOG: `${API_URL}api/logbook/by-aor`,
  MARK_IMP: `${API_URL}api/logbook/toggle-important`,
  DELETE_LOG: `${API_URL}api/logbook`,
  UPDATE_LOG: `${API_URL}api/logbook`,
  LOGBOOK_EXPORT_PDF: `${API_URL}api/logbook/export/pdf`,
  LOGOUT: `${API_URL}api/auth/logout`,
  COMPANIES: `${API_URL}api/company/admin`,
  CATEGORY: `${API_URL}api/categories/admin`,
  ROLE: `${API_URL}api/roles/admin`,
  THEMES: `${API_URL}api/themes/admin`,
  FETCH_AOR: `${API_URL}api/aor/admin`,
  FETCH_USERS: `${API_URL}api/users/admin/show`,
  USER_ADD: `${API_URL}api/users/admin`,
  USER_IMPORT: `${API_URL}api/users/admin/import`,
  STATES: `${API_URL}api/states`,
  CITIES: `${API_URL}api/cities`,
  FACILITIES: `${API_URL}api/facilities/admin`,
  QOS: `${API_URL}api/quality-of-sleep/admin`,
  FACILITY_IMPORT: `${API_URL}api/facilities/admin/import`,
  FACILITY_AOR: `${API_URL}api/facilities/`,
  AOR_FORMS: `${API_URL}api/aor-form-templates/admin/show`,
  AOR_FORMS_ACTION: `${API_URL}api/aor-form-templates/admin`,
  AOR_TEMPLATE: `${API_URL}api/aor-form-templates/aors`,
  FACILITY_COMPANY: `${API_URL}api/facilities/companies`,
  FACILITY_COMPANY_AORS: `${API_URL}api/facilities/companies/`,
  WEATHER_BY_AOR: `${API_URL}api/dashboard/weather/byaor`,
  REMAINING_SHIFT_TIME: `${API_URL}api/dashboard/timer`,
  WORK_STATS: `${API_URL}api/dashboard/work-stats`,
  IMPERSONATE: `${API_URL}api/auth/impersonate`,
  END_AOR: `${API_URL}api/shift/endByAor`,

  AOR_USERS: `${API_URL}api/users`,

  NOTIFICATIONS: `${API_URL}api/notifications/user`,
  NOTIFICATION_READALL: `${API_URL}api/notifications/read/readall`,
  NOTIFICATION_READID: `${API_URL}api/notifications/read`,

  FETCH_PROFILE: `${API_URL}api/auth/profile`,

  MITIGATION: `${API_URL}api/fatigue-mitigation/admin`,
  SLEEP_HOURS: `${API_URL}api/continuous-sleep/admin`,
  SHIFT_HOURS: `${API_URL}api/hours-of-shift/admin`,
  HITCH_DAY: `${API_URL}api/hitch-day-offset/admin`,
  FATIGUE_SCORE: `${API_URL}api/fatigue-score/admin`,
  TIMEZONES: `${API_URL}api/timezones`,

  FATIGUE_MITIGATION: `${API_URL}api/fatigue-mitigation`,
  APPLY_MITIGATION: `${API_URL}api/fatigue-management/apply`,
  ACTIVE_SHIFT_MITIGATIONS: `${API_URL}api/fatigue-management/user-mitigations`,
  STOP_TIMER: `${API_URL}api/fatigue-management/stop-timer`,
  RECENT_SHIFTS: `${API_URL}api/shift/recent`,
  CURRENT_SHIFT_FATIGUE_SCORE: `${API_URL}api/fatigue-management/score`,
  START_TIMER: `${API_URL}api/timer/start`,
  TIMER_VIEW: `${API_URL}api/timer/view`,
  PAUSE_TIMER: `${API_URL}api/timer/pause`,
  RESUME_TIMER: `${API_URL}api/timer/resume`,
  STOP_REMAINDER_TIMER: `${API_URL}api/timer/stop`,
  RECENT_ACTIVITY: `${API_URL}api/logbook/recent`,
};
